version: "3"
services:
  db:
    build:
      context: ./postgres
      dockerfile: Dockerfile
  admin:
    links:
      - db
    depends_on:
      - db
    image: fenglc/pgadmin4:latest
    ports:
      - "5050:5050"
  web:
    links:
      - db
    depends_on:
      - db
    build:
      context: ./web
      dockerfile: Dockerfile
    working_dir: /web
    ports:
      - "8080:5000"